export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    DASHBOARD: '/dashboard',
    SUBSCRIPTIONS: '/subscriptions',
    SUBSCRIPTION_DETAIL: '/subscriptions/:id',
    CREATE_SUBSCRIPTION: '/subscriptions/new',
    CUSTOMERS: '/customers',
    CUSTOMER_DETAIL: '/customers/:id',
    INVOICES: '/invoices',
    INVOICE_DETAIL: '/invoices/:id',
    PAYMENTS: '/payments',
    PRODUCTS: '/products',
    PRODUCT_DETAIL: '/products/:id',
    WEBHOOKS: '/webhooks',
    SETTINGS: '/settings',
    SESSIONS: '/sessions',
    NOTIFICATIONS: '/notifications',
    PRIVACY_POLICY: '/privacy',
    TERMS_OF_SERVICE: '/terms',
    COOKIE_POLICY: '/cookies',
};
